name: firmware_build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: arduino/compile-sketches@v1.0.1
      with:
        fqbn: arduino:mbed:nano33ble
        sketch-paths: |
          - software/firmware
        libraries: |
          - Mbed BLE HID@v1.3.0
